-- Active Substances από EMA Article 57
-- Παράχθηκε από preprocess_ema.py

SET FOREIGN_KEY_CHECKS=0;

SET NAMES 'utf8mb4';
INSERT IGNORE INTO Active_Substances (id, name) VALUES
  (1, 'Liquid Extract From Viscum Album Subsp. Abietis Var Abies Alba (1:20)'),
  (2, 'Extraction Solvents: Water For Injection And Sodium Chloride (99.91:0.09)'),
  (3, 'Vitamin A Concentrate (Oily Form)'),
  (4, 'Synthetic'),
  (5, 'Acetylsalicylic Acid'),
  (6, 'Hypericum Perforatum L.'),
  (7, 'Tincture From Agnus Castus Fruit (1:10)'),
  (8, 'Extraction Solvent: Ethanol 69.5% V/V'),
  (9, 'Benzocaine'),
  (10, 'Dexamethasone Base'),
  (11, 'Estriol'),
  (12, 'Reproterol Hydrochloride'),
  (13, 'Sodium Cromoglicate'),
  (14, 'Chlorphenamine Maleate'),
  (15, 'Phenylephrine Bitartrate'),
  (16, 'Paracetamol'),
  (17, 'Abacavir'),
  (18, 'Lamivudine'),
  (19, 'Zidovudine'),
  (20, 'Abacavir Sulfate'),
  (21, 'Dabigatran Etexilate'),
  (22, 'Pefloxacin'),
  (23, 'Rivaroxaban'),
  (24, 'Insulin Glargine'),
  (25, 'Apixaban'),
  (26, 'Atorvastatin'),
  (27, 'Fentanyl'),
  (28, 'Brivaracetam'),
  (29, 'Abiraterone Acetate'),
  (30, 'Amoxicillin'),
  (31, 'Clavulanic Acid'),
  (32, 'Tranylcypromine'),
  (33, 'Erythromycin'),
  (34, 'Erythromycin Ethylsuccinate'),
  (35, 'Soft Extract Of Capsicum'),
  (36, '(4-7: 1)'),
  (37, 'Corresponding To 4.8 Mg Of Capsaicinoids'),
  (38, 'Calculated As Capsaicin. Extraction Solvent: Ethanol 80% (V/V)'),
  (39, 'Capsaicin'),
  (40, 'Cayenne Pepper Soft Extract'),
  (41, 'Nonivamide'),
  (42, 'Paracetamol Bp'),
  (43, 'Fluid Extract From Gentian Root (1: 1)'),
  (44, 'Extraction Solvent: Ethanol 50% (V / V)'),
  (45, 'Fluid Extract Of Wormwood (1:1)'),
  (46, 'Extraction Solvent: Ethanol 20% (V/V)'),
  (47, 'Fluid Extract From Melissa Leaf (1: 1)'),
  (48, 'Fluid Extract From Acorus Calamus Root (1:1)'),
  (49, 'Fluid Extract From Angelica Root (1: 1)'),
  (50, 'Extraction Solvent: Ethanol 30% (V/V)'),
  (51, 'Sodium Hydrogen Carbonate'),
  (52, 'Potassium Chloride'),
  (53, 'Sodium Chloride'),
  (54, 'Macrogol 3350'),
  (55, 'Lactic Acid'),
  (56, 'Salicylic Acid'),
  (57, 'Sildenafil Citrate'),
  (58, 'Idecabtagene Vicleucel'),
  (59, 'Calcium'),
  (60, 'Magnesium'),
  (61, 'Sildenafil'),
  (62, 'Amphotericin B'),
  (63, 'Aripiprazole'),
  (64, 'Drospirenone'),
  (65, 'Ethinylestradiol'),
  (66, 'Rosuvastatin Calcium'),
  (67, 'Prucalopride'),
  (68, 'Lactose Monohydrate'),
  (69, 'Prucalopride Succinate'),
  (70, 'Bendroflumethiazide'),
  (71, 'Naltrexone Hydrochloride'),
  (72, 'Irbesartan'),
  (73, 'Amlodipine'),
  (74, 'Bevacizumab'),
  (75, 'Fentanyl Citrate'),
  (76, 'Castor Oil'),
  (77, 'Virgin'),
  (78, 'Sennae Folium'),
  (79, 'Refined'),
  (80, 'Magnesium Sulfate Heptahydrate'),
  (81, 'Senna Pods'),
  (82, 'Tinnevelly'),
  (83, 'Metformin Hydrochloride'),
  (84, 'Fluocinolone Acetonide'),
  (85, 'Framycetin'),
  (86, 'Retinol Palmitate'),
  (87, 'Riboflavin Sodium Phosphate'),
  (88, 'Thiamine Hydrochloride'),
  (89, 'Ascorbic Acid'),
  (90, 'Ergocalciferol'),
  (91, 'Nicotinamide'),
  (92, 'Pyridoxine Hydrochloride'),
  (93, 'Ibuprofen'),
  (94, 'Abietic Acid'),
  (95, 'Esomeprazole Magnesium Dihydrate'),
  (96, 'Isoconazole Nitrate'),
  (97, 'Moxifloxacin'),
  (98, 'Neomycin'),
  (99, 'Chlorobutanol'),
  (100, 'Menthol'),
  (101, 'Camphor'),
  (102, 'Cineole'),
  (103, 'Sylvestris Pine Oil'),
  (104, 'Moxifloxacin Hydrochloride'),
  (105, 'Bimatoprost'),
  (106, 'Abiraterone'),
  (107, 'Prednisolone'),
  (108, 'Amlodipine Besilate'),
  (109, 'Bilastine'),
  (110, 'Hydrocortisone'),
  (111, 'Viscum Album Abietis Ex Herba Recente Col. D30'),
  (112, 'Extract Of Fresh Fir Mistletoe Herb'),
  (113, 'Extract Of Fresh Almond Mistletoe Herb'),
  (114, 'Extract Of Fresh Birch Mistletoe Herb'),
  (115, 'Extract Of Fresh Hawthorn Mistletoe Herb'),
  (116, 'Extract Of Fresh Ash Mistletoe Herb'),
  (117, 'Extract Of Apple Tree Mistletoe (1:50)'),
  (118, 'Extraction Solvents: Sodium Monohydrogen Phosphate Dihydrate'),
  (119, 'Water For Injections (2.03:0.34:97.63)'),
  (120, 'Extract Of Fresh Pine Mistletoe Herb'),
  (121, 'Extract Of Fresh Oak Mistletoe Herb'),
  (122, 'Ginkgo Biloba Extract'),
  (123, 'Echinacea Dil. D2'),
  (124, 'Gelsemium Sempervirens Dil. D4'),
  (125, 'Ammi Visnaga Dil. D 2'),
  (126, 'Blatta Orientalis Urt.'),
  (127, 'Cetraria Islandica Dil. D 3'),
  (128, 'Datura Stramonium Dil. D 4'),
  (129, 'Euspongia Officinalis Dil. D 3'),
  (130, 'Natrium Sulfuricum Dil. D 4'),
  (131, 'Selenicereus Grandiflorus Dil. D 1'),
  (132, 'Matricaria Recutita Dil. D3'),
  (133, 'Grindelia Robusta Mother Tincture'),
  (134, 'Eriodictyon Californicum Dil. D2'),
  (135, 'Psychotria Ipecacuanha Dil. D4'),
  (136, 'Drosera Dil. D2'),
  (137, 'Bortezomib'),
  (138, 'Brimonidine Tartrate'),
  (139, 'Fluocinonide'),
  (140, 'Hexetidine'),
  (141, 'Ruscogenin'),
  (142, 'Paclitaxel Albumin-Bound'),
  (143, 'Fluticasone Propionate'),
  (144, 'Formoterol Fumarate Dihydrate'),
  (145, 'Dry Extract Of Hederae Folium (5-7.5:1)'),
  (146, 'Extraction Solvent: Ethanol 30% (M/M)'),
  (147, 'Ibandronic Acid'),
  (148, 'Vortioxetine'),
  (149, 'Ambroxol Hydrochloride'),
  (150, 'Respiratory Syncytial Virus'),
  (151, 'Subgroup A'),
  (152, 'Stabilized Prefusion F Protein 847a'),
  (153, 'Subgroup B'),
  (154, 'Stabilized Prefusion F Protein 847b'),
  (155, 'Epoetin Alfa'),
  (156, 'Sodium Valproate'),
  (157, 'Artemisia Absinthium Ex Herba Siccata'),
  (158, 'Ethanol. Infusum Ø'),
  (159, 'Terebinthina Laricina Dil. D3'),
  (160, 'Ezetimibe'),
  (161, 'Terebinthina Laricina'),
  (162, 'Terebinthinae Aetheroleum Rectificatum'),
  (163, 'Betulae Folium'),
  (164, 'Sage Leaf (Salvia Officinalis)'),
  (165, 'Thyme'),
  (166, 'Matricariae Flos'),
  (167, 'Melissa Leaf'),
  (168, 'Oxycodone Hydrochloride'),
  (169, 'Beta-Alanine'),
  (170, 'Paclitaxel'),
  (171, 'Febuxostat'),
  (172, 'Potassium Citrate'),
  (173, 'Travoprost'),
  (174, 'Acamprosate Calcium'),
  (175, 'Ramipril'),
  (176, 'Risedronate Sodium'),
  (177, 'Calcium Carbonate, Cholecalciferol Concentrate'),
  (178, 'Acarbose'),
  (179, 'Carvedilol'),
  (180, 'Benzyl Benzoate'),
  (181, 'Dermatophagoides Pteronyssinus'),
  (182, 'Dermatophagoides Farinae'),
  (183, 'Phenylephrine Hydrochloride'),
  (184, 'Pseudoephedrine Hydrochloride'),
  (185, 'Triprolidine Hydrochloride'),
  (186, 'Azelastine Hydrochloride'),
  (187, 'Oxymetazoline Hydrochloride'),
  (188, 'Dextromethorphan Hydrobromide'),
  (189, 'Acetylcysteine'),
  (190, 'Filgrastim'),
  (191, 'Colecalciferol'),
  (192, 'Iohexol'),
  (193, 'Glucose'),
  (194, 'Anhydrous'),
  (195, 'Magnesium Chloride Hexahydrate'),
  (196, 'Calcium Chloride Dihydrate'),
  (197, 'Levothyroxine Sodium'),
  (198, 'Metronidazole'),
  (199, 'Bisoprolol Fumarate'),
  (200, 'Acebutolol Hydrochloride'),
  (201, 'Acebutolol'),
  (202, 'Diclofenac Sodium'),
  (203, 'Aceclofenac'),
  (204, 'Hydrochlorothiazide'),
  (205, 'Lisinopril'),
  (206, 'Captopril'),
  (207, 'Caffeine'),
  (208, 'Adapalene'),
  (209, 'Benzoyl Peroxide'),
  (210, 'Cefoperazone'),
  (211, 'Citalopram Hydrochloride'),
  (212, 'Penfluridol'),
  (213, 'Acemetacin'),
  (214, 'Acetazolamide'),
  (215, 'Glucosamine Hydrochloride'),
  (216, 'Acenocoumarol'),
  (217, 'Ciprofloxacin'),
  (218, 'Methylprednisolone Aceponate'),
  (219, 'Aminocaproic Acid'),
  (220, 'Allopurinol Sodium'),
  (221, 'Benzoic Acid'),
  (222, 'Malic Acid'),
  (223, '(S)-Lactic Acid'),
  (224, 'Perindopril Arginine'),
  (225, 'Enalapril Maleate'),
  (226, 'Piracetam'),
  (227, 'Terlipressin'),
  (228, 'Cyproterone Acetate'),
  (229, 'Eslicarbazepine Acetate'),
  (230, 'Eslicarbazepine'),
  (231, 'Glatiramer Acetate'),
  (232, 'Potassium Acetate'),
  (233, 'Sodium Acetate'),
  (234, 'Acetazolamide Bp'),
  (235, 'Acetazolamide Ph. Eur.'),
  (236, 'Cetirizine Dihydrochloride'),
  (237, 'Acetylcholine Chloride'),
  (238, 'Water For Injection'),
  (239, 'Lysine Aspirin'),
  (240, 'Calcium-Sodium-Hydrogencitrate (6:6:3:7)'),
  (241, 'Acetylleucine'),
  (242, 'Acetylsalicylic Acid Ph. Eur.'),
  (243, 'Aciclovir'),
  (244, 'Folic Acid'),
  (245, 'Aesculus'),
  (246, 'Cortex'),
  (247, 'Ethanol. Decoctum Dil. D3'),
  (248, 'Antimonit Dil. D8'),
  (249, 'Gentiana Lutea'),
  (250, 'Hamamelis'),
  (251, 'Millefolium Dil. D1'),
  (252, 'Aciclovir Sodium'),
  (253, 'Aciclovir Bp'),
  (254, 'Acitretin'),
  (255, 'Alendronic Acid'),
  (256, 'Alendronate Sodium Trihydrate'),
  (257, 'Thioctic Acid'),
  (258, 'Tranexamic Acid'),
  (259, 'Zoledronic Acid'),
  (260, 'Zoledronic Acid Monohydrate'),
  (261, 'Pantoprazole Sodium Sesquihydrate'),
  (262, 'Esomeprazole'),
  (263, 'Omeprazole'),
  (264, 'D'),
  (265, 'l-Lysine Acetylsalicylate'),
  (266, 'Alendronate Sodium Monohydrate'),
  (267, 'Sodium Alendronate Trihydrate Ph. Eur.'),
  (268, 'Carglumic Acid'),
  (269, 'Fusidic Acid'),
  (270, 'Gadoteric Acid'),
  (271, 'Mycophenolic Acid'),
  (272, 'Tiaprofenic Acid'),
  (273, 'Ursodeoxycholic Acid'),
  (274, 'Anhydrous Zoledronic Acid'),
  (275, 'Calcium Carbonate'),
  (276, 'Sodium Alginate'),
  (277, 'Potassium Hydrogen Carbonate'),
  (278, 'Magnesium Carbonate Heavy'),
  (279, 'Boric Acid'),
  (280, 'Alendronate Sodium'),
  (281, 'Sodium Picosulfate'),
  (282, 'Magnesium Oxide'),
  (283, 'Citric Acid'),
  (284, 'Clodronate Disodium Tetrahydrate'),
  (285, 'Lidocaine Hydrochloride'),
  (286, 'Folic Acid Hydrate'),
  (287, 'Ibandronate Sodium Hydrate'),
  (288, 'Sodium Ibandronate'),
  (289, 'Mycophenolate Sodium'),
  (290, 'Trichloroacetic Acid'),
  (291, 'Valproic Acid'),
  (292, 'Icosapent Ethyl'),
  (293, 'Docosahexaenoic Acid Ethyl Ester'),
  (294, 'Doconexent'),
  (295, 'Icosapent'),
  (296, 'Omega-3-Acid Ethyl Esters 90'),
  (297, 'Acidum Alpha-Ketoglutaricum D200'),
  (298, 'Acidum Alpha-Ketoglutaricum D30'),
  (299, 'Acidum Alpha-Ketoglutaricum D10'),
  (300, 'Acidum Cis-Aconiticum D30'),
  (301, 'Acidum Cis-Aconiticum D200'),
  (302, 'Acidum Cis-Aconiticum D10'),
  (303, 'Acidum Citricum D10'),
  (304, 'Acidum Citricum D200'),
  (305, 'Acidum Citricum D30'),
  (306, 'Acidum Malicum D200'),
  (307, 'Acidum Malicum D30'),
  (308, 'Acidum Malicum D10'),
  (309, 'Acidum Formicicum Dil D12'),
  (310, 'Acidum Formicicum Dil. D30'),
  (311, 'Acidum Formicicum Dil. D200'),
  (312, 'Acidum Fumaricum D200'),
  (313, 'Acidum Fumaricum D30'),
  (314, 'Acidum Fumaricum D10'),
  (315, 'Nicotinic Acid'),
  (316, 'Acidum Phosphoricum Dil. D30'),
  (317, 'Acidum Phosphoricum Dil. D200'),
  (318, 'Acidum Phosphoricum Dil. D12'),
  (319, 'Acidum Succinicum D10'),
  (320, 'Acidum Succinicum D200'),
  (321, 'Acidum Succinicum D30'),
  (322, 'Natrium Sulfuricum Dil. D12'),
  (323, 'Acidum Arsenicosum Dil. D8'),
  (324, 'Secale Cornutum Dil. D4'),
  (325, 'Pantoprazole'),
  (326, 'Ferrous Gluconate'),
  (327, 'Rabeprazole Sodium'),
  (328, 'Buprenorphine'),
  (329, 'L-Methionine'),
  (330, 'Mefenamic Acid'),
  (331, 'Phenoxymethylpenicillin'),
  (332, 'Diethylamine Salicylate'),
  (333, 'Piperacillin Sodium'),
  (334, 'Tazobactam Sodium'),
  (335, 'Escitalopram Oxalate'),
  (336, 'Pregabalin'),
  (337, 'Celecoxib'),
  (338, 'Clopidogrel'),
  (339, 'Ticlopidine Hydrochloride'),
  (340, 'Human Antithrombin'),
  (341, 'Tretinoin'),
  (342, 'Isotretinoin'),
  (343, 'Clindamycin'),
  (344, 'Miconazole Nitrate'),
  (345, 'Clindamycin Phosphate'),
  (346, 'Hydrous'),
  (347, 'Chlorhexidine Gluconate Solution Bp'),
  (348, 'Chlorhexidine Gluconate'),
  (349, 'Zinc Acetate'),
  (350, 'Anhydrous Benzoyl Peroxide'),
  (351, 'Magnesium Phosphoricum D8'),
  (352, 'Aconitum Napellus D4'),
  (353, 'Acidum Arsenicosum D30'),
  (354, 'Acidum Arsenicosum Dil. D30'),
  (355, 'Magnesium Phosphoricum Dil. D8'),
  (356, 'Gnaphalium Polycephalum Dil. D3'),
  (357, 'Aconitum Dil. D4'),
  (358, 'Citrullus Colocynthis Dil. D4'),
  (359, 'Gnaphalium Polycephalum Dil. D4'),
  (360, 'Aconitum Dil. D6'),
  (361, 'Dexpanthenol'),
  (362, 'Aconitum Napellus D30'),
  (363, 'Lidocaine Hydrochloride Monohydrate'),
  (364, 'Topiramate'),
  (365, 'Naphazoline Hydrochloride'),
  (366, 'D-Camphor'),
  (367, 'Lavender Oil'),
  (368, 'Quarz Dil. D9 Oleos. (Hab'),
  (369, 'Vs. 8a Und 12j In Raffiniertem Erdnussöl)'),
  (370, 'Aconitum Napellus E Tubere Ferm 33c Dil. D9 Oleos. (Hab'),
  (371, 'Vs. 33c Und 12j'),
  (372, 'In Raffiniertem Erdnussöl)'),
  (373, 'Aconitum Napellus E Tubere Ferm 33c Dil. D29 (Hab'),
  (374, 'Vs. 33c)'),
  (375, 'Atropa Belladonna E Radice Ferm 33b Dil. D29 (Hab'),
  (376, 'Vs. 33b)'),
  (377, 'Toxicodendron Quercifolium E Foliis Ferm 33d Dil. D29 (Hab'),
  (378, 'Vs. 33d)'),
  (379, 'Aconitum Napellus E Tubere W 5% (Hab'),
  (380, 'Vs. 12g Mit Nativem Olivenöl)'),
  (381, 'Aconitum Napellus Rh Dil. D3'),
  (382, 'Bryonia Trit. D 3'),
  (383, 'Ferrum Phosphoricum Trit D 2'),
  (384, 'Belladonna Trit. D3'),
  (385, 'Aconitum Trit. D3'),
  (386, 'Gelsemium Trit. D3'),
  (387, 'Aconitum Napellus E Tubere Ferm 33c Dil. D2 (Hab'),
  (388, 'Bryonia Cretica Ferm 33b Dil. D2'),
  (389, 'Cinchona Succirubra E Cortice Ferm 35b Dil. D1 (Hab'),
  (390, 'Vs. 35b)'),
  (391, 'Eucalyptus Globulus E Foliis Ferm 33d Dil. D1 (Hab'),
  (392, 'Eupatorium Cannabinum Ex Herba Ferm 33c Dil. D1 (Hab'),
  (393, 'Eucalyptus Globulus Dil. D2'),
  (394, 'Aconitum Napellus Dil. D2'),
  (395, 'Aconitum Napellus Dil. D10'),
  (396, 'Aconitum Napellus Dil. D30'),
  (397, 'Aconitum Napellus Dil. D200'),
  (398, 'Eucalyptus Globulus Dil. D10'),
  (399, 'Eucalyptus Globulus Dil. D30'),
  (400, 'Psychotria Ipecacuanha Dil. D10'),
  (401, 'Psychotria Ipecacuanha Dil. D30'),
  (402, 'Psychotria Ipecacuanha Dil. D200'),
  (403, 'Psychotria Ipecacuanha Dil. D2'),
  (404, 'Anhydrous Tiotropium Bromide'),
  (405, 'Tadalafil'),
  (406, 'Budesonide'),
  (407, 'Etoricoxib'),
  (408, 'Chloroquine'),
  (409, 'Sterilised Water For Injections'),
  (410, 'Acrivastine'),
  (411, 'Phenoxymethylpenicillin Potassium'),
  (412, 'Nimesulide'),
  (413, 'Montelukast'),
  (414, 'Telmisartan'),
  (415, 'Arnica Montana C4'),
  (416, 'Cimicifuga Racemosa C4'),
  (417, 'Sanguinaria Canadensis C4'),
  (418, 'Nitroglycerinum C4'),
  (419, 'Lachesis C5'),
  (420, 'Haemophilus Type B Conjugate Vaccine (Tetanus Toxoid Conjugate)'),
  (421, 'Tetanus Protein'),
  (422, 'Charcoal'),
  (423, 'Activated'),
  (424, 'Doxycycline Monohydrate'),
  (425, 'Xylometazoline Hydrochloride'),
  (426, 'Diphenhydramine Hydrochloride, Paracetamol'),
  (427, 'Pseudoephedrine Hydrochloride, Paracetamol'),
  (428, 'Guaifenesin'),
  (429, 'Fluorouracil'),
  (430, 'Deanol Acetamidobenzoate'),
  (431, 'Hesperidin Methyl Chalcone'),
  (432, 'Magnesium Glycerophosphate'),
  (433, 'Lidocaine'),
  (434, 'Alteplase'),
  (435, 'Magnesium Pidolate'),
  (436, 'Modafinil'),
  (437, 'Morphine Sulfate'),
  (438, 'Octenidine Dihydrochloride'),
  (439, 'Phenoxyethanol'),
  (440, 'Saccharomyces Cerevisiae Type D Extract'),
  (441, 'Sodium Disulfide'),
  (442, 'Promethazine Hydrochloride'),
  (443, 'Carbocisteine'),
  (444, 'Betacarotene'),
  (445, 'Biotin'),
  (446, 'Cyanocobalamin'),
  (447, 'Phytomenadione'),
  (448, 'Pyridoxine'),
  (449, 'Riboflavin'),
  (450, 'Rutoside'),
  (451, 'Thiamine'),
  (452, 'Zinc'),
  (453, 'Chromium'),
  (454, 'Copper'),
  (455, 'Iodine'),
  (456, 'Iron'),
  (457, 'Manganese'),
  (458, 'Pantothenic Acid'),
  (459, 'Phosphorus'),
  (460, 'Selenium'),
  (461, 'Retinol'),
  (462, 'Alpha-Tocopherol'),
  (463, 'Molybdenum'),
  (464, 'Lutein'),
  (465, 'P-Aminobenzoic Acid'),
  (466, 'Lycopene'),
  (467, 'Boron'),
  (468, 'Vanadium'),
  (469, 'Glycine'),
  (470, 'Succinic Acid'),
  (471, 'Norethisterone Acetate'),
  (472, 'Estradiol'),
  (473, 'Etofenamate'),
  (474, 'Pelargonium Sidoides Dc Root Liquid Extract'),
  (475, 'Hydrocortisone Sodium Phosphate'),
  (476, 'Colecalciferol, Calcium Carbonate'),
  (477, 'Risedronate Monosodium'),
  (478, 'Atropine Sulfate'),
  (479, 'Peppermint Oil'),
  (480, 'Aluminium Hydroxide Gel'),
  (481, 'Dried'),
  (482, 'Magnesium Carbonate'),
  (483, 'Magnesium Trisilicate'),
  (484, 'Pioglitazone'),
  (485, 'Urokinase'),
  (486, 'Deproteinised Hemoderivative Of Calf Blood'),
  (487, 'Insulin Human'),
  (488, 'Naproxen Sodium'),
  (489, 'Hedera Helix Dry Extract'),
  (490, 'Ethanol 30%'),
  (491, 'Benzydamine Hydrochloride'),
  (492, 'Nitrous Oxide'),
  (493, 'Oxygen'),
  (494, 'Quinapril Hydrochloride'),
  (495, 'Ketorolac Trometamol'),
  (496, 'Galantamine'),
  (497, 'Hypromellose'),
  (498, 'Nefopam'),
  (499, 'Quinapril'),
  (500, 'Atracurium Besilate'),
  (501, 'Loperamide Hydrochloride'),
  (502, 'Denosumab'),
  (503, 'Magnesium Hydroxide'),
  (504, 'Aluminium Hydroxide-Magnesium Carbonate Co-Dried Gel'),
  (505, 'Algeldrate'),
  (506, 'Solifenacin Succinate'),
  (507, 'Aluminium Phosphate'),
  (508, 'Diphtheria Toxoid'),
  (509, 'Tetanus Toxoid'),
  (510, 'Pertussis Toxoid'),
  (511, 'Pertussis Filamentous Haemagglutinin'),
  (512, 'Pertussis Pertactin'),
  (513, 'Pertussis Fimbrial Agglutinogens (Fim) 2 And 3'),
  (514, 'Poliovirus (Inactivated) Type 3 (Saukett Strain)'),
  (515, 'Poliovirus (Inactivated) Type 2 (Mef-1 Strain)'),
  (516, 'Poliovirus (Inactivated) Type 1 (Mahoney Strain)'),
  (517, 'Doxazosin Mesilate'),
  (518, 'Dutasteride'),
  (519, 'Melatonin'),
  (520, 'Sitagliptin'),
  (521, 'Nifedipine'),
  (522, 'Thiocolchicoside'),
  (523, 'Etonogestrel'),
  (524, 'Ceftobiprole Medocaril Sodium'),
  (525, 'Tramadol Hydrochloride'),
  (526, 'Temgicoluril'),
  (527, 'Eleutherococci Radix Dry Extract (16-25:1)'),
  (528, 'Delapril Hydrochloride'),
  (529, 'Manidipine Dihydrochloride'),
  (530, 'Ropinirole'),
  (531, 'Finasteride'),
  (532, 'Loxapine'),
  (533, 'Tamsulosin Hydrochloride'),
  (534, 'Memantine Hydrochloride'),
  (535, 'Brentuximab Vedotin'),
  (536, 'Sodium Molybdate Dihydrate'),
  (537, 'Zinc Chloride'),
  (538, 'Ferric Chloride Hexahydrate'),
  (539, 'Potassium Iodide'),
  (540, 'Sodium Fluoride'),
  (541, 'Chromium Chloride Hexahydrate'),
  (542, 'Copper Chloride Dihydrate'),
  (543, 'Manganese Chloride Tetrahydrate'),
  (544, 'Sodium Selenite Anhydrous'),
  (545, 'Sodium Selenite'),
  (546, 'Copper Gluconate'),
  (547, 'Manganese Gluconate'),
  (548, 'Zinc Gluconate'),
  (549, 'Chromic Chloride'),
  (550, 'Sodium Molybdate'),
  (551, 'Ferrous Gluconate Hydrate Ph.Eur.'),
  (552, 'Zinc Gluconate (Ph. Eur.)'),
  (553, 'Methylphenidate Hydrochloride'),
  (554, 'Ammonium Chloride'),
  (555, 'Potassium Hydroxide'),
  (556, 'Dipotassium Hydrogen Phosphate Trihydrate'),
  (557, 'Trometamol'),
  (558, 'Betamethasone'),
  (559, 'Disodium Phosphate Dihydrate'),
  (560, 'Potassium Dihydrogen Phosphate'),
  (561, 'Hyoscine Butylbromide'),
  (562, 'Ampicillin'),
  (563, 'Desogestrel'),
  (564, 'Prednisolone Sodium Phosphate'),
  (565, 'Riociguat'),
  (566, 'Adenosine'),
  (567, 'Phytolacca Americana Dil. D4'),
  (568, 'Clematis Recta D1'),
  (569, 'Scrophularia Nodosa Ø'),
  (570, 'Adenosinum Triphosphoricum D200'),
  (571, 'Adenosinum Triphosphoricum D30'),
  (572, 'Adenosinum Triphosphoricum D6'),
  (573, 'Adenosinum Triphosphoricum D10'),
  (574, 'Levonorgestrel'),
  (575, 'Amitriptyline Hydrochloride'),
  (576, 'Lanolin'),
  (577, 'Everolimus'),
  (578, 'Glyceryl Trinitrate'),
  (579, 'Camellia Sinensis'),
  (580, 'Trimetazidine Dihydrochloride'),
  (581, 'Dexamfetamine Sulfate'),
  (582, 'Sulfadiazine'),
  (583, 'Lisinopril Dihydrate'),
  (584, 'Nystatin'),
  (585, 'Dienogest'),
  (586, 'Dienogest, Ethinylestradiol'),
  (587, 'Lactose.'),
  (588, 'Dimethyl Fumarate'),
  (589, 'Tamoxifen'),
  (590, 'Tamoxifen Citrate'),
  (591, 'Desmopressin'),
  (592, 'Anastrozole'),
  (593, 'Lisdexamfetamine Dimesylate'),
  (594, 'Diltiazem Hydrochloride'),
  (595, 'Polysorbate 80'),
  (596, 'Squalene'),
  (597, 'Split Influenza Virus (Inactivated) Of Strain A/Vietnam/1194/2004 (H5n1) Like Strain Used (Nibrg-14)'),
  (598, 'Dl-Alpha-Tocopherol'),
  (599, 'Sertraline Hydrochloride'),
  (600, 'Berberis Vulgaris D12'),
  (601, 'Cardiospermum Halicacabum D12'),
  (602, 'Acidum Formicicum D12'),
  (603, 'Natrium Chloratum D12'),
  (604, 'Thryallis Glauca D12'),
  (605, 'Zincum Isovalerianicum D12'),
  (606, 'Calcium Carbonicum Hahnemanni D6'),
  (607, 'Delphinium Staphisagria D6'),
  (608, 'Calcium Fluoratum D6'),
  (609, 'Matricaria Recutita D4'),
  (610, 'Podophyllum Peltatum D6'),
  (611, 'Atropa Bella-Donna D8'),
  (612, 'Ambra Grisea D12'),
  (613, 'Argentum Nitricum D12'),
  (614, 'Kalium Bromatum D12'),
  (615, 'Phosphorus D12'),
  (616, 'Acidum Formicicum D 6'),
  (617, 'Euphrasia 3c D4'),
  (618, 'Lobaria Pulmonaria D4'),
  (619, 'Allium Cepa D4'),
  (620, 'Schoenocaulon Officinale D4'),
  (621, 'Kalium Chloratum D6'),
  (622, 'Acidum Silicicum D6'),
  (623, 'Berberis Vulgaris D6'),
  (624, 'Thuja Occidentalis D4'),
  (625, 'Zincum Metallicum D12'),
  (626, 'Nicotiana Tabacum D12'),
  (627, 'Veratrum Album D4'),
  (628, 'Anamirta Cocculus D4'),
  (629, 'Strychnos Nux-Vomica D6'),
  (630, 'Tenoxicam'),
  (631, 'Allopurinol'),
  (632, 'Tapentadol'),
  (633, 'Schoenocaulon Officinale Dil. D3'),
  (634, 'Spigelia Anthelmia Dil. D 3'),
  (635, 'Menyanthes Trifoliata Dil. D3'),
  (636, 'Piper Methysticum Spag. Peka Dil. D8'),
  (637, 'Aconitum Napellus Dil. D12'),
  (638, 'Bryonia Spag. Peka Dil. D3'),
  (639, 'Semecarpus Anacardium Dil. D6'),
  (640, 'Naloxone Hydrochloride'),
  (641, 'Dexketoprofen'),
  (642, 'Healing Earth'),
  (643, 'Propyphenazone'),
  (644, 'Ibuprofen Lysine'),
  (645, 'Adonis Vernalis Ferm 33d Dil. D2'),
  (646, 'Crataegus Laevigata/Monogyna E Foliis Et Fructibus Ferm 33d Dil. D2 (Hab'),
  (647, 'Kalmia Latifolia Dil. D 2'),
  (648, 'Adonis Vernalis Dil. D4'),
  (649, 'Nerium Oleander Dil. D4'),
  (650, 'Cactus Dil. D2'),
  (651, 'Kalium Carbonicum Dil. D3'),
  (652, 'Crataegus Dil. D2'),
  (653, 'Tacrolimus'),
  (654, 'Zolpidem Tartrate'),
  (655, 'Risperidone'),
  (656, 'Epinephrine'),
  (657, 'Epinephrine Bitartrate'),
  (658, 'Epinephrine Hydrochloride'),
  (659, 'Adrenaline Acid Tartrate Bp'),
  (660, 'Carbazochrome'),
  (661, 'Iodine (123i) Iobenguane'),
  (662, 'Doxorubicin Hydrochloride'),
  (663, 'Anagrelide'),
  (664, 'Levodropropizine'),
  (665, 'Acidum Formicicum D8'),
  (666, 'Histaminum Dihydrochloricum D22'),
  (667, 'Histaminum Dihydrochloricum D8'),
  (668, 'Ledum Palustre D8'),
  (669, 'Acidum Sulfuricum D22'),
  (670, 'Arctium D8'),
  (671, 'Pix Liquida D10'),
  (672, 'Tellurium Metallicum D10'),
  (673, 'Histaminum Dihydrochloricum D12'),
  (674, 'Arnica Montana D6'),
  (675, 'Acidum Arsenicosum D8'),
  (676, 'Lycopodium Clavatum D6'),
  (677, 'Selenium D12'),
  (678, 'Stibium Sulfuratum Nigrum D10'),
  (679, 'Strychnos Ignatii D6'),
  (680, 'Graphites D10'),
  (681, 'Sulfur D12'),
  (682, 'Thuja Occidentalis D6'),
  (683, 'Lacosamide'),
  (684, 'Tralokinumab'),
  (685, 'Donepezil Hydrochloride'),
  (686, 'Glycerol'),
  (687, 'Cetylpyridinium Chloride'),
  (688, 'Oxazepam'),
  (689, 'Octocog Alfa'),
  (690, 'Temozolomide'),
  (691, 'Fesoterodine'),
  (692, 'Eribulin Mesylate'),
  (693, 'Rurioctocog Alfa Pegol'),
  (694, 'Radamts13'),
  (695, 'Olanzapine'),
  (696, 'Helium'),
  (697, 'Carbon Monoxide'),
  (698, 'Air'),
  (699, 'Medicinal'),
  (700, 'Flunisolide'),
  (701, 'Beclometasone Dipropionate'),
  (702, 'Desloratadine'),
  (703, 'Pseudoephedrine Sulphate'),
  (704, 'Salmeterol'),
  (705, 'Simeticone'),
  (706, 'Terbutaline Sulfate'),
  (707, 'Dimeticone'),
  (708, 'Metoclopramide'),
  (709, 'Salbutamol'),
  (710, 'Fluticasone Furoate'),
  (711, 'Bisacodyl'),
  (712, 'Isoflurane'),
  (713, 'Escin'),
  (714, 'Dry Extract From Horse-Chestnut Equivalent To 1.1 - 2.5 G Fresh Seeds Corresponding To 50 Mg Aescin'),
  (715, 'Extraction Solvent: Ethanol 68% (V/V)'),
  (716, 'Aesculus Hippocastanum L. Seed Dry Extract'),
  (717, 'Hippocastani Corticis Extractum Siccum'),
  (718, 'Aesculus Hippocastanum D2'),
  (719, 'Arnica Montana Dil D2'),
  (720, 'Collinsonia Canadensis Dil. D1'),
  (721, 'Aesculus Hippocastanum Dil. D1'),
  (722, 'Carduus Marianus Dil. D1'),
  (723, 'Calcium Fluoratum Dil. D6'),
  (724, 'Aesculus Hippocastanum E Semine La 25% Sicc. (Hab'),
  (725, 'Vs. 12m)'),
  (726, 'Borago Officinalis Ex Herba La 20% (Hab'),
  (727, 'Vs. 12c)'),
  (728, 'Prunus Spinosa E Fructibus La 25% (Hab'),
  (729, 'Vs. 12o)'),
  (730, 'Quercus Robur/Petraea E Cortice'),
  (731, 'Decoctum La 10% (Hab'),
  (732, 'Vs. 12k)'),
  (733, 'Solidago Virgaurea Ex Herba La 20% (Hab'),
  (734, 'Vipera Berus Dil. D12'),
  (735, 'Placenta Totalis Suis D30'),
  (736, 'Pulsatilla Pratensis Dil. D30'),
  (737, 'Aesculus Hippocastanum Dil. D30'),
  (738, 'Atropa Bella-Donna Dil. D12'),
  (739, 'Silybum Marianum Dil. D12'),
  (740, 'Calcium Fluoratum Dil. D30'),
  (741, 'Secale Cornutum Dil. D30'),
  (742, 'Daphne Mezereum Dil. D12'),
  (743, 'Hamamelis Virginiana Dil. D6'),
  (744, 'Aesculus Hippocastanum Dil. D12'),
  (745, 'Aesculus Hippocastanum Dil. D200'),
  (746, 'Aesculus Hippocastanum Dil. D6'),
  (747, 'Secale Cornutum Dil. D8'),
  (748, 'Dry Extract Of Horse-Chestnut Corresponding To 21 Mg Of Triterpene Glycosides'),
  (749, 'Expressed As Protoaescigenin: Extraction Solvent: Ethanol 50% (M/M)'),
  (750, 'Aesculus Seed Dry Extract'),
  (751, 'Standardised'),
  (752, 'Dry Extract Of Horse Chestnut'),
  (753, 'Standardised (Der 5-7:1)'),
  (754, 'Adjusted To 12.5 Mg Of Triterpene Glycosides Calculated As Protoaescigenin'),
  (755, 'Extraction Solvent: Ethanol 50% (M/M)'),
  (756, 'Nicotiana Tabacum Dil D6'),
  (757, 'Potentilla Anserina Dil. D6'),
  (758, 'Cuprum Aceticum Dil. D6'),
  (759, 'Veratrum Album Dil. D6'),
  (760, 'Secale Cornutum Dil. D6'),
  (761, 'Lauromacrogol 400'),
  (762, 'Ethyl Chloride'),
  (763, 'Voriconazole'),
  (764, 'Fosfomycin Trometamol'),
  (765, 'Afatinib Dimaleate'),
  (766, 'Afatinib'),
  (767, 'Fluoxetine'),
  (768, 'Paroxetine'),
  (769, 'Metamizole Sodium Monohydrate'),
  (770, 'Apremilast'),
  (771, 'Metoclopramide Hydrochloride'),
  (772, 'Aflibercept'),
  (773, 'Cefixime Trihydrate'),
  (774, 'Dexamethasone Phosphate'),
  (775, 'Triflusal'),
  (776, 'Sertraline'),
  (777, 'Alclometasone Dipropionate'),
  (778, 'Fluconazole'),
  (779, 'Mirtazapine'),
  (780, 'Eupatorium Perfoliatum D4'),
  (781, 'Baptisia Tinctoria D4'),
  (782, 'Ferrum Phosphoricum D8'),
  (783, 'Gelsemium Sempervirens D6'),
  (784, 'Aconitum Napellus D6'),
  (785, 'Euphorbium D6'),
  (786, 'Hydrargyrum Biiodatum D12'),
  (787, 'Luffa Operculata D12'),
  (788, 'Pulsatilla Pratensis D6'),
  (789, 'Sinapis Nigra D2'),
  (790, 'Bryonia D6'),
  (791, 'Gentiana Lutea D1'),
  (792, 'Ferrum Phosphoricum D12'),
  (793, 'Acidum Lacticum D12'),
  (794, 'Lachesis D 12'),
  (795, 'Mercurius Solubilis Hahnemanni D12'),
  (796, 'Phytolacca Americana D6'),
  (797, 'Atropa Bella-Donna D6'),
  (798, 'Salvia Officinalis D1'),
  (799, 'Fluphenazine Decanoate'),
  (800, 'A/Turkey/Turkey/1/05 (H5n1)-Like Strain (Nibrg-23)'),
  (801, 'Alprazolam'),
  (802, 'Theophylline Anhydrous'),
  (803, 'Fosfomycin'),
  (804, 'Theophylline'),
  (805, 'Levomenthol'),
  (806, 'Resorcinol'),
  (807, 'Thymol'),
  (808, 'Methotrexate'),
  (809, 'Lonoctocog Alfa'),
  (810, 'Zinc Sulphate'),
  (811, 'Benzalkonium Chloride'),
  (812, 'Hydrocortisone Hydrogen Succinate'),
  (813, 'Fulvestrant'),
  (814, 'Atomoxetine'),
  (815, 'Vamorolone'),
  (816, 'Pentoxifylline'),
  (817, 'Tenofovir Disoproxil'),
  (818, 'Nintedanib'),
  (819, 'Argentum Metallicum Praeparatum Dil. D6 Aquos.'),
  (820, 'Aspidium Filix-Mas'),
  (821, 'Spora Dil. D3'),
  (822, 'Conchae Dil. D7 Aquos.'),
  (823, 'Amanita Muscaria Dil. D8'),
  (824, 'Phosphorus Dil. D6'),
  (825, 'Vildagliptin'),
  (826, 'Meropenem Anhydrous'),
  (827, 'Meropenem'),
  (828, 'Tirofiban Hydrochloride Monohydrate'),
  (829, 'Levofloxacin'),
  (830, 'Ticagrelor'),
  (831, 'Dantrolene Sodium'),
  (832, 'Ispaghula Seed'),
  (833, 'Ispaghula Husk'),
  (834, 'Cassia Angustifolia Vahl. (Polvo De Frutos)'),
  (835, 'Trihexyphenidyl Hydrochloride'),
  (836, 'Cinnarizine'),
  (837, 'Dimenhydrinate'),
  (838, 'Meloxicam'),
  (839, 'Dry Extract From Agnus Castus Fruit (7-13:1)'),
  (840, 'Extraction Solvent: 60% M/M'),
  (841, 'Dry Extract From Chaste Tree Fruits (7-11:1)'),
  (842, 'Extraction Solvent: Ethanol 70% (V/V)'),
  (843, 'Agnus Castus Ø'),
  (844, 'Pulsatilla Trit D3'),
  (845, 'Rosmarinus Officinalis Trit D2'),
  (846, 'Apis Mellifica Trit D3'),
  (847, 'Dry Extract From Agnus Castus Fruit Equivalent To 23.4-31.2 Mg Of Fruit'),
  (848, 'Extraction Solvent: Ethanol 75% (V/V)'),
  (849, 'Agnus Castus Fruit Dry Extract (10-16:1)'),
  (850, 'Vitex Agnus-Castus Mother Tincture'),
  (851, 'Cimicifuga Racemosa Dil. D 2'),
  (852, 'Zincum Valerianicum Dil. D3'),
  (853, 'Pulsatilla Dil. D4'),
  (854, 'Dry Extract From Chaste Tree Fruits (7-13:1)'),
  (855, 'Extraction Solvent: Ethanol 60% (M/M)'),
  (856, 'Agomelatine'),
  (857, 'Progesterone'),
  (858, 'Agomelatine Citric Acid'),
  (859, 'Lansoprazole'),
  (860, 'Levomethadone Hydrochloride'),
  (861, 'Testosterone Isobutyrate'),
  (862, 'Ferrum Sidereum D10'),
  (863, 'Aurum Metallicum D10'),
  (864, 'Clopidogrel Hydrogen Sulfate'),
  (865, 'Minoxidil'),
  (866, 'Agropyron Repens E Radice Ferm 33c Dil. D3 (Hab'),
  (867, 'Kalium Carbonicum E Cinere Fagi Silvaticae Dil. D9 Aquos. (Hab'),
  (868, 'Vs. 5b)'),
  (869, 'Taraxacum Officinale E Planta Tota Ferm 34c Dil. D4 (Hab'),
  (870, 'Vs. 34c)'),
  (871, 'Zinnober Dil. D6'),
  (872, 'Coriandrum Sativum'),
  (873, 'Hyssopus Officinalis'),
  (874, 'Matricaria Recutita'),
  (875, 'Tila Tomentosa'),
  (876, 'Melissa Officinalis'),
  (877, 'Angelica Archangelica Root'),
  (878, 'Lemon Verbena'),
  (879, 'Nutmeg'),
  (880, 'Cinnamomum Zeylanicum'),
  (881, 'Hydrogen Peroxide'),
  (882, 'Meclozine Hydrochloride'),
  (883, 'Ethanol (96 Per Cent)'),
  (884, 'Oxaceprol'),
  (885, 'Brinzolamide'),
  (886, 'Drospirenone, Ethinylestradiol'),
  (887, 'Ethinylestradiol, Levonorgestrel'),
  (888, 'Lactose Anhydrous'),
  (889, 'Acidum Arsenicosum Dil. D6'),
  (890, 'Silybum Marianum D15'),
  (891, 'Cinchona Pubescens Spag. Peka D6'),
  (892, 'Glechoma Hederacea Spag. Peka D6'),
  (893, 'Grindelia Robusta Spag. Peka D6'),
  (894, 'Ceanothus Americanus D4'),
  (895, 'Amanita Muscaria D4'),
  (896, 'Human Coagulation Factor Ix'),
  (897, 'Erenumab'),
  (898, 'Dienogest, Estradiol Valerate'),
  (899, 'Estradiol Valerate'),
  (900, 'Placebo'),
  (901, 'Artemether'),
  (902, 'Lumefantrine'),
  (903, 'Ciclesonide'),
  (904, 'Fluticasone'),
  (905, 'Salmeterol Xinafoate'),
  (906, 'Tiotropium'),
  (907, 'Allergen Extract From Pollen Of Dactylis Glomerata'),
  (908, 'Anthoxanthum Odoratum'),
  (909, 'Lolium Perenne'),
  (910, 'Poa Pratensis And Phleum Pratense'),
  (911, 'Benzododecinium Bromide 10% Solution'),
  (912, 'Fremanezumab'),
  (913, 'Bromazepam'),
  (914, 'Polihexanide'),
  (915, 'Niraparib'),
  (916, 'Quetiapine'),
  (917, 'Verapamil Hydrochloride'),
  (918, 'Biperiden Hydrochloride'),
  (919, 'Latanoprost'),
  (920, 'Timolol Maleate'),
  (921, 'Lorazepam'),
  (922, 'Gestodene'),
  (923, 'Trifarotene'),
  (924, 'Clonazepam'),
  (925, 'Carbo Vegetabilis'),
  (926, 'Caraway Oil'),
  (927, 'Bitter Fennel Fruit Oil'),
  (928, 'Amethyst'),
  (929, 'Betula Pendula Ferm 34e Ø'),
  (930, 'Cochlearia Officinalis Ex Herba Ferm 33b Ø (Hab'),
  (931, 'Fucus Vesiculosus E Planta Tota Ferm 51 Ø (Hab'),
  (932, 'Vs. 51)'),
  (933, 'Fumaria Officinalis Ex Herba Ferm 33c Ø (Hab'),
  (934, 'Graphites Dil. D11 Aquos.'),
  (935, 'Juniperus Communis E Fructibus Ferm 35a Ø (Hab'),
  (936, 'Vs. 35a)'),
  (937, 'Oxalis Acetosella E Planta Tota Ferm 34b Ø (Hab'),
  (938, 'Vs. 34b)'),
  (939, 'Rhamnus Frangula E Cortice Ferm 33e Ø (Hab'),
  (940, 'Vs. 33e)'),
  (941, 'Rosa E Floribus Ferm Cum Ferro Ø (Hab'),
  (942, 'Vs. 37a)'),
  (943, 'Tropaeolum Majus Ex Herba Ferm 33b Ø (Hab'),
  (944, 'Urtica Dioica E Planta Tota Ferm 33c Ø (Hab'),
  (945, 'Viola Tricolor Ex Herba Ferm 33e Ø (Hab'),
  (946, 'Sulfur Dil. D6'),
  (947, 'Rhus Toxicodendron Dil. D6'),
  (948, 'Zinc Oxide'),
  (949, 'Ichthammol'),
  (950, 'Clindamycin Hydrochloride'),
  (951, 'Tropaeolum Majus Ex Herba La 20% (Hab'),
  (952, 'Aesculus Hippocastanum E Cortice'),
  (953, 'Anthyllis Vulneraria Ex Herba La 20% (Hab'),
  (954, 'Bellis Perennis Ex Herba La 20% (Hab'),
  (955, 'Calendula Officinalis E Floribus La 20% (Hab'),
  (956, 'Cutis Feti Bovis Gl Dil. D5 (Hab'),
  (957, 'Vs. 41b)'),
  (958, 'Echinacea Pallida Ex Herba La 20% (Hab'),
  (959, 'Funiculus Umbilicalis Bovis Gl Dil. D5 (Hab'),
  (960, 'Glandula Suprarenalis Bovis Gl Dil. D5 (Hab'),
  (961, 'Vs. 41a)'),
  (962, 'Placenta Bovis Gl Dil. D5 (Hab'),
  (963, 'Sodium Bituminosulfonate Light'),
  (964, 'Nabumetone'),
  (965, 'Cafedrine Hydrochloride'),
  (966, 'Theodrenaline Hydrochloride'),
  (967, 'Glycopyrronium Bromide'),
  (968, 'Axitinib'),
  (969, 'Amoxicillin Sodium'),
  (970, 'Imiquimod'),
  (971, 'Amisulpride'),
  (972, 'Isopropyl Alcohol'),
  (973, 'Cola Dil. D2'),
  (974, 'Camphora D3'),
  (975, 'Crataegus Mother Tincture'),
  (976, 'Zingiber Officinale D3'),
  (977, 'Solidago Virgaurea Mother Tincture'),
  (978, 'Pulsatilla Pratensis D4'),
  (979, 'Acidum Benzoicum E Resina D4'),
  (980, 'Acidum Nitricum D4'),
  (981, 'Apis Mellifica D3'),
  (982, 'Lytta Vesicatoria D4'),
  (983, 'Populus Tremuloides D2'),
  (984, 'Acidum Benzoicum E Resina Dil. D4'),
  (985, 'Lytta Vesicatoria Dil. D 4'),
  (986, 'Populus Tremuloides Spag. Peka D2'),
  (987, 'Pulsatilla Pratensis Spag. Peka D4'),
  (988, 'Apis Mellifica Dil. D3'),
  (989, 'Inosine Pranobex'),
  (990, 'Palonosetron'),
  (991, 'Fosnetupitant'),
  (992, 'Beclometasone Dipropionate Anhydrous'),
  (993, '5-Aminolevulinic Acid'),
  (994, 'Allantoin'),
  (995, 'Aloe Juice Dried'),
  (996, 'Powdered'),
  (997, 'Frangulae Corticis Extractum Siccum'),
  (998, 'Betamethasone Sodium Phosphate'),
  (999, 'Cilostazol'),
  (1000, 'St. John''s Wort Dry Extract (3.5-6.0:1)');

INSERT IGNORE INTO Active_Substances (id, name) VALUES
  (1001, 'Albendazole'),
  (1002, 'Amylmetacresol'),
  (1003, '2'),
  (1004, '4 Dichlorobenzyl Alcohol'),
  (1005, 'Bromhexine Hydrochloride'),
  (1006, 'Labetalol Hydrochloride'),
  (1007, 'Apis Mellifera Venom'),
  (1008, 'Clotrimazole'),
  (1009, 'Candida Albicans E Volumine Cellulae (Lyophil.'),
  (1010, 'Steril.) D3'),
  (1011, 'Steril.) D4'),
  (1012, 'Steril.) D5'),
  (1013, 'Lisinopril Anhydrous'),
  (1014, 'Human Serum Albumin'),
  (1015, 'Olmesartan Medoxomil'),
  (1016, 'Human Albumin Solution'),
  (1017, 'Policresulen'),
  (1018, 'Pemetrexed Diacid Monohydrate'),
  (1019, 'Human Plasma Protein'),
  (1020, 'Iodinated (125i) Human Serum Albumin'),
  (1021, 'Proxymetacaine Hydrochloride'),
  (1022, 'Trometamol Citrate'),
  (1023, 'Anhydrous Disodium Citrate'),
  (1024, 'Dipotassium Hydrogen Citrate'),
  (1025, 'Clonidine Hydrochloride'),
  (1026, 'Allii Sativi Extractum'),
  (1027, 'Echinaceae Purpureae Herbae'),
  (1028, 'Alfuzosin Hydrochloride'),
  (1029, '2-Propanol (Ph. Eur.)'),
  (1030, 'Ethanol 70 %'),
  (1031, 'Ethanol 70% (V/V)'),
  (1032, 'Sodium Oleate'),
  (1033, 'Simvastatin'),
  (1034, '1-Propanol'),
  (1035, 'Rosuvastatin'),
  (1036, 'Sodium Oxybate'),
  (1037, 'Altizide'),
  (1038, 'Spironolactone'),
  (1039, 'Potassium Canrenoate'),
  (1040, 'Eplerenone'),
  (1041, 'Paliperidone'),
  (1042, 'Warfarin Sodium'),
  (1043, 'Framycetin Sulfate'),
  (1044, 'Triamcinolone Acetonide'),
  (1045, 'Chlortalidone'),
  (1046, 'Methyldopa'),
  (1047, 'Lormetazepam'),
  (1048, 'Timolol'),
  (1049, 'Laronidase'),
  (1050, 'Alectinib Hydrochloride'),
  (1051, 'Carbidopa'),
  (1052, 'Levodopa'),
  (1053, 'Alendronate Sodium (Ph. Eur.)'),
  (1054, 'Cholecalciferol Concentrate (Powder Form)'),
  (1055, 'Refined And Standardized Dry Extract Of Milk Thistle Fruit (24-27:1)'),
  (1056, 'Extraction Solvent: Acetone And Water (95:5)'),
  (1057, 'Phenobarbital'),
  (1058, 'Anhydrous Caffeine'),
  (1059, 'Fexofenadine Hydrochloride'),
  (1060, 'Betamethasone Valerate'),
  (1061, 'Antazoline Phosphate'),
  (1062, 'Levocetirizine Dihydrochloride'),
  (1063, 'Rupatadine'),
  (1064, 'Loratadine'),
  (1065, 'Mometasone Furoate'),
  (1066, 'Dimetindene Maleate'),
  (1067, 'Alfacalcidol'),
  (1068, 'Letrozole'),
  (1069, 'Isoprenaline Hydrochloride'),
  (1070, 'Cytarabine'),
  (1071, 'Alpha Amylase'),
  (1072, 'Naphazoline Nitrate'),
  (1073, 'Tetracycline Hydrochloride'),
  (1074, 'Ceftazidime'),
  (1075, 'Human Alpha1-Proteinase Inhibitor'),
  (1076, 'Terazosin'),
  (1077, 'Hydrocortisone Butyrate'),
  (1078, 'Diclofenac Diethylamine'),
  (1079, 'Chloramphenicol'),
  (1080, 'Colistimethate Sodium'),
  (1081, 'Tetracycline'),
  (1082, 'Cefaclor'),
  (1083, 'Cefaclor Monohydrate'),
  (1084, 'Alfentanil Hydrochloride'),
  (1085, 'Alfentanil'),
  (1086, 'Betahistine Dihydrochloride'),
  (1087, 'Bioactive Concentrate Of Small Marine Fish'),
  (1088, 'Alimemazine Tartrate'),
  (1089, 'Alfuzosin'),
  (1090, 'Myrtecaine'),
  (1091, 'Diethylamine'),
  (1092, 'Codeine Phosphate Hemihydrate'),
  (1093, 'Pitofenone Hydrochloride'),
  (1094, 'Fenpiverinium Bromide'),
  (1095, 'Diphenhydramine Hydrochloride'),
  (1096, 'Metamizole Magnesium'),
  (1097, 'Clonixin Lysinate'),
  (1098, 'Guaiacol'),
  (1099, 'Methyl Salicylate'),
  (1100, 'Mephenesin'),
  (1101, 'Hydroxyethyl Salicylate'),
  (1102, 'Methyl Nicotinate'),
  (1103, 'Turpentine Oil'),
  (1104, 'Codeine Phosphate'),
  (1105, 'Drotaverine Hydrochloride'),
  (1106, 'Goserelin'),
  (1107, 'Metamizole Sodium'),
  (1108, 'Concizumab'),
  (1109, 'Duloxetine'),
  (1110, 'Alimemazine'),
  (1111, 'Pemetrexed'),
  (1112, 'Alitretinoin'),
  (1113, 'Pitavastatin'),
  (1114, 'Indometacin'),
  (1115, 'Apis Mellifera (801)'),
  (1116, 'Aluminium Hydroxide'),
  (1117, 'Alternaria Alternata (402)'),
  (1118, 'Histamine Dihydrochloride'),
  (1119, 'Betaine Citrate'),
  (1120, 'Sodium Citrate Ph. Eur.'),
  (1121, 'Chlorhexidine Dihydrochloride'),
  (1122, 'Vespula Spp. (802)'),
  (1123, 'Melphalan'),
  (1124, 'Artemisia Vulgaris (312)'),
  (1125, 'Alphatocopherol Acetate'),
  (1126, 'Heparin Sodium'),
  (1127, 'Frovatriptan'),
  (1128, 'Euphrasia 3c D6'),
  (1129, 'Argentum Nitricum D6'),
  (1130, 'Sabadilla D6'),
  (1131, 'Apis Mellifica D6'),
  (1132, 'Acidum Formicicum Dil D6'),
  (1133, 'Cuprum Metallicum Dil. D6'),
  (1134, 'Levocabastine'),
  (1135, 'Thryallis Glauca D4'),
  (1136, 'Luffa Operculata D6'),
  (1137, 'Cardiospermum Halicacabum D4'),
  (1138, 'Apis Mellifica Dil. D4'),
  (1139, 'Acidum Formicicum Dil. D 4'),
  (1140, 'Hydrocotyle Asiatica D3'),
  (1141, 'Cardiospermum Dil. D2'),
  (1142, 'Galphimia Glauca Dil. D3'),
  (1143, 'Luffa Operculata Dil. D4'),
  (1144, 'Mometasone Furoate Monohydrate'),
  (1145, 'Aralia Racemosa D3'),
  (1146, 'Acidum Arsenicosum D6'),
  (1147, 'Chloropyramine Hydrochloride'),
  (1148, 'Ketotifen Hydrogen Fumarate'),
  (1149, 'Orchard Grass Pollen Allergoid'),
  (1150, 'Chemically Modified'),
  (1151, 'Meadow Fescue Pollen Allergoid'),
  (1152, 'Kentucky Blue Grass Pollen Allergoid'),
  (1153, 'Velvet Grass Pollen Allergoid'),
  (1154, 'Rye Grass Pollen Allergoid'),
  (1155, 'Timothy Grass Pollen Allergoid'),
  (1156, 'Betula, Corylus Avellana, Alnus, Aluminium Hydroxide'),
  (1157, 'Betula, Corylus Avellana, Alnus, Aluminium Hydroxide, Beech'),
  (1158, 'Artemisia Vulgaris'),
  (1159, 'Betula'),
  (1160, 'Alnus'),
  (1161, 'Corylus Avellana'),
  (1162, 'Triticum Aestivum'),
  (1163, 'Phleum Pratense'),
  (1164, 'Holcus Lanatus'),
  (1165, 'Dactylis Glomerata'),
  (1166, 'Festuca Pratensis'),
  (1167, 'Poa Pratensis'),
  (1168, 'Secale Cereale'),
  (1169, 'Oat'),
  (1170, 'Hordeum Vulgare'),
  (1171, 'Wall Pellitory'),
  (1172, 'Aluminium Hydroxide, Rye Pollen Allergoid, Chemically Modified, Orchard Grass Pollen Allergoid, Chemically Modified, Meadow Fescue Pollen Allergoid, Chemically Modified, Kentucky Blue Grass Pollen Allergoid, Chemically Modified, Velvet Grass Pollen Allergoid, Chemically Modified, Rye Grass Pollen Allergoid, Chemically Modified, Timothy Grass Pollen Allergoid, Chemically Modified'),
  (1173, 'Phleum Pratense, Holcus Lanatus, Aluminium Hydroxide, Dactylis Glomerata, Festuca Pratensis, Lolium Perenne, Poa Pratensis, Secale Cereale'),
  (1174, 'Aluminium Hydroxide, Rye Pollen Allergoid, Chemically Modified, Orchard Grass Pollen Allergoid, Chemically Modified, Mugwort Pollen Allergoid, Chemically Modified, Meadow Fescue Pollen Allergoid, Chemically Modified, Kentucky Blue Grass Pollen Allergoid, Chemically Modified, Velvet Grass Pollen Allergoid, Chemically Modified, Rye Grass Pollen Allergoid, Chemically Modified, Timothy Grass Pollen Allergoid, Chemically Modified'),
  (1175, 'Phleum Pratense, Holcus Lanatus, Artemisia Vulgaris, Aluminium Hydroxide, Dactylis Glomerata, Festuca Pratensis, Lolium Perenne, Poa Pratensis, Secale Cereale'),
  (1176, 'Aluminium Hydroxide, Birch Pollen Allergoid, Chemically Modified, Rye Pollen Allergoid, Chemically Modified, Orchard Grass Pollen Allergoid, Chemically Modified, Meadow Fescue Pollen Allergoid, Chemically Modified, Kentucky Blue Grass Pollen Allergoid, Chemically Modified, Velvet Grass Pollen Allergoid, Chemically Modified, Rye Grass Pollen Allergoid, Chemically Modified, Timothy Grass Pollen Allergoid, Chemically Modified'),
  (1177, 'Betula, Phleum Pratense, Holcus Lanatus, Aluminium Hydroxide, Dactylis Glomerata, Festuca Pratensis, Lolium Perenne, Poa Pratensis, Secale Cereale'),
  (1178, 'Aluminium Hydroxide, Rye Pollen Allergoid, Chemically Modified, Orchard Grass Pollen Allergoid, Chemically Modified, Meadow Fescue Pollen Allergoid, Chemically Modified, Kentucky Blue Grass Pollen Allergoid, Chemically Modified, Velvet Grass Pollen Allergoid, Chemically Modified, Rye Grass Pollen Allergoid, Chemically Modified, Plantain Pollen Allergoid, Chemically Modified, Timothy Grass Pollen Allergoid, Chemically Modified'),
  (1179, 'Plantago Lanceolata, Phleum Pratense, Holcus Lanatus, Aluminium Hydroxide, Dactylis Glomerata, Festuca Pratensis, Lolium Perenne, Poa Pratensis, Secale Cereale'),
  (1180, 'Plantago Lanceolata'),
  (1181, 'Aluminium Hydroxide, Rye Pollen Allergoid, Chemically Modified, Orchard Grass Pollen Allergoid, Chemically Modified, Mugwort Pollen Allergoid, Chemically Modified, Meadow Fescue Pollen Allergoid, Chemically Modified, Kentucky Blue Grass Pollen Allergoid, Chemically Modified, Velvet Grass Pollen Allergoid, Chemically Modified, Rye Grass Pollen Allergoid, Chemically Modified, Plantain Pollen Allergoid, Chemically Modified, Timothy Grass Pollen Allergoid, Chemically Modified'),
  (1182, 'Plantago Lanceolata, Phleum Pratense, Holcus Lanatus, Artemisia Vulgaris, Aluminium Hydroxide, Dactylis Glomerata, Festuca Pratensis, Lolium Perenne, Poa Pratensis, Secale Cereale'),
  (1183, 'Aluminium Hydroxide, Birch Pollen Allergoid, Chemically Modified, Rye Pollen Allergoid, Chemically Modified, Orchard Grass Pollen Allergoid, Chemically Modified, Meadow Fescue Pollen Allergoid, Chemically Modified, Kentucky Blue Grass Pollen Allergoid, Chemically Modified, Velvet Grass Pollen Allergoid, Chemically Modified, Rye Grass Pollen Allergoid, Chemically Modified, Plantain Pollen Allergoid, Chemically Modified, Timothy Grass Pollen Allergoid, Chemically Modified'),
  (1184, 'Betula, Plantago Lanceolata, Phleum Pratense, Holcus Lanatus, Aluminium Hydroxide, Dactylis Glomerata, Festuca Pratensis, Lolium Perenne, Poa Pratensis, Secale Cereale'),
  (1185, 'Racemic'),
  (1186, 'Pumilio Pine Oil'),
  (1187, 'Orlistat'),
  (1188, 'Urticae Folium'),
  (1189, 'Allium Sativum'),
  (1190, 'Allium Sativum Bulb'),
  (1191, 'Allium Cepa Trit. D4'),
  (1192, 'Garlic Powder'),
  (1193, 'Nettle Leaf Powder'),
  (1194, 'Dry Animal Bile Powder'),
  (1195, 'Allopurinol Bp'),
  (1196, 'Allopurinol (Ph. Eur.)'),
  (1197, 'Olopatadine'),
  (1198, 'Dry Extract Of Valerian Root (5 - 8:1 )'),
  (1199, 'Extraction Solvent : Methanol 45 % (M / M)'),
  (1200, 'Dry Extract Of Hop Cones (7 - 10:1): Extract Solvent: Methanol 45% (M / M)'),
  (1201, 'Botulinum Toxin Type A - Haemagglutinin Complex'),
  (1202, 'Almagate'),
  (1203, 'Flecainide Acetate'),
  (1204, 'Salbutamol Sulfate'),
  (1205, 'Ipratropium Bromide'),
  (1206, 'Valsartan'),
  (1207, 'Light'),
  (1208, 'Aluminium Aminoacetate'),
  (1209, 'Perindopril Tert-Butylamine'),
  (1210, 'Almotriptan'),
  (1211, 'Almotriptan Malate');

SET FOREIGN_KEY_CHECKS=1;
